/* Replace with your SQL commands */
CREATE TABLE notes (id SERIAL NOT NULL, body varchar NOT NULL, authorId uuid NOT NULL, bugId uuid NOT NULL, createdAt TIMESTAMP NOT NULL DEFAULT now(), updatedAt TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT PK_notes PRIMARY KEY (id));
ALTER TABLE notes ADD CONSTRAINT FK_notes1 FOREIGN KEY (authorId) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE notes ADD CONSTRAINT FK_notes2 FOREIGN KEY (bugId) REFERENCES bugs(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
