/* Replace with your SQL commands */
CREATE TABLE members(id SERIAL NOT NULL, projectId uuid NOT NULL, memberId uuid NOT NULL, joinedAt TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT PK_members PRIMARY KEY (id));

ALTER TABLE members ADD CONSTRAINT FK_members1 FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE members ADD CONSTRAINT FK_members2 FOREIGN KEY (memberId) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
